[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
  # Secrets scanning configuration
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY", SECRETS_SCAN_OMIT_PATHS = "docs/**,postman/**" }

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*.cjs"]

# Redirect API calls to Netlify Functions
# Using status 200 for rewrites (not redirects) to preserve POST method
[[redirects]]
  from = "/api/chat/completions"
  to = "/.netlify/functions/chat-completions"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
