[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/chat/completions"
  to = "/.netlify/functions/chat-completions"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
