[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
  # Secrets scanning configuration
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY", SECRETS_SCAN_OMIT_PATHS = "docs/**,postman/**" }

[functions]
  node_bundler = "esbuild"
  # Use Node.js 18.x for functions
  node_version = "18"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/chat/completions"
  to = "/.netlify/functions/chat-completions"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
