[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Secrets scanning configuration
[build.environment]
  # Disable secrets scanning for public Supabase anon key (it's meant to be public)
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY"
  # Omit documentation files from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = "docs/**,postman/**"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/chat/completions"
  to = "/.netlify/functions/chat-completions"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
